# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Smoke-Database
version:      1.17
version_from: lib/Test/Smoke/Database.pm
installdirs:  site
requires:
    CGI:                           0
    Data::Dumper:                  0
    DBD::mysql:                    0
    DBI:                           0
    News::NNTPClient:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
